# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import builtins as module_0
import algorithms.linkedlist.is_cyclic as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    object_0 = module_0.object()
    module_1.is_cyclic(object_0)


def test_case_1():
    none_type_0 = None
    node_0 = module_1.Node(none_type_0)
    var_0 = module_1.is_cyclic(none_type_0)
    assert var_0 is False
    node_1 = module_1.Node(none_type_0)
    var_1 = module_0.object()
    var_2 = module_1.is_cyclic(node_1)
    assert var_2 is False


def test_case_2():
    bytes_0 = b"\x8eu\xe3\xc6"
    node_0 = module_1.Node(bytes_0)


def test_case_3():
    bytes_0 = b"\x8e\x10u\xe3\xc6"
    node_0 = module_1.Node(bytes_0)
    var_0 = module_1.is_cyclic(node_0)
    assert var_0 is False
