# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.map.valid_sudoku as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = 0.1
    module_0.is_valid_sudoku(float_0)
