# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.longest_common_subsequence as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "VhXc'"
    var_0 = module_0.longest_common_subsequence(str_0, str_0)
    assert var_0 == 5
    object_0 = module_1.object()
    module_0.longest_common_subsequence(object_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.longest_common_subsequence(none_type_0, none_type_0)
