# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.maths.sqrt_precision_factor as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    var_0 = module_0.square_root(bool_0)
    assert var_0 == pytest.approx(1.0003048780487804, abs=0.01, rel=0.01)
    set_0 = set()
    bytes_0 = b"&\xae\xb3x\x17\xc2\xddT\xf6\x11q\x8b\xd3\x80u\x1d\n\xfac`"
    module_0.square_root(bytes_0, set_0)


def test_case_1():
    bool_0 = False
    var_0 = module_0.square_root(bool_0)
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
