# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.domain_extractor as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = " Recursive Implementation "
    var_0 = module_0.domain_name_1(str_0)
    assert var_0 == " Recursive Implementation "
    module_1.object(**var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"s\xf5zM\xe2d\xe9!\xf4\xc2\xc9\xd2\xd1\xd1\x9d"
    module_0.domain_name_2(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "\n    Reference : https://en.wikipedia.org/wiki/Sorting_algorithm#Exchange_sort\n    Complexity : O(n^2)\n    "
    var_0 = module_0.domain_name_1(str_0)
    assert var_0 == "wikipedia"
    var_1 = module_0.domain_name_2(str_0)
    assert var_1 == "en"
    none_type_0 = None
    module_0.domain_name_1(none_type_0)
