# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.linkedlist.linkedlist as module_0


def test_case_0():
    bool_0 = False
    singly_linked_list_node_0 = module_0.SinglyLinkedListNode(bool_0)


def test_case_1():
    bool_0 = False
    doubly_linked_list_node_0 = module_0.DoublyLinkedListNode(bool_0)
